efemerides = {
    "01":{
        "01":"Año Nuevo",
        "02":"Día de los reyes magos",
        "15":"Día del redactor publicitario",
    },
    "02":{
        "13":"Día mundial de la radio",
        "14":"Día de San Valentín",
        "15":"Día del redactor publicitario",
    },
    "03":{
        "01":"Día nacional del transporte",
        "03":"Día mundial de la vida silvestre",
        "05":"Día nacional del gas",
        "06":"Día del escultor",
        "08":"Día de la mujer",
        "12":"Día del Escudo nacional",
        "14":"Día de las escuelas de frontera",
        "15":"Día mundial de los derechos del consumidor",
        "18":"Día del trabajador telefónico",
        "19":"Día del artesano",
        "21":"Comienza el otoño",
        "22":"Día mundial del agua",
        "27":"Día mundial del teatro",
    },
    "04":{
        "02":"Día del Veterano y de los Caídos en la Guerra las Malvinas",
        "03":"Día del obrero maderero",
        "07":"Día mundial de la Salud",
        "14":"Día de las Américas",
        "29":"Día del animal",
    },
    "05":{
        "01":"Día del trabajador",
        "09":"Día Internacional de las Aves",
        "12":"Día internacional de las enfermeras",
        "14":"Día del futbolista argentino",
        "15":"Día Internacional de las Familias",
        "17":"Día mundial de las telecomunicaciones",
        "18":"Día de la escarapela",
        "23":"Día nacional del cine",
        "25":"Revolución de mayo",
        "28":"Día de la maestra jardinera",
        "29":"Día nacional del folclorista",
        "31":"Día nacional de la energía atómica",
    },
    "06":{
        "06":"Día de la ingeniería argentina",
        "10":"Día nacional de la seguridad vial",
        "13":"Día del escritor",
        "15":"Día nacional del libro",
        "16":"Día del ingeniero",
        "20":"Día de la bandera",
        "21":"Día del apicultor",
    },
    "07":{
        "01":"Día del historiador",
        "09":"Declaración de la independencia argentina",
        "17":"Día del automovilismo deportivo",
        "20":"Día del amigo",
        "23":"Día del payador",
        "27":"Día del antropólogo",
        "29":"Día de la cultura nacional",   
    },
    "08":{
        "01":"Día de la Pacha-Mama",
        "06":"Día del ingeniero agrónomo",
        "09":"Día internacional de las poblaciones indígenas",
        "10":"Día nacional de la Fuerza Aérea",
        "12":"Día internacional de la juventud",
        "17":"Día de San Martín",
        "22":"Día del folclore",
        "26":"Día internacional del actor",
        "27":"Día de la radiodifusión",
        "29":"Día nacional del árbol",
    },
    "09":{
        "02":"Día de la Industria",
        "11":"Día del maestro",
        "19":"Día del instrumentador quirúrgico",
        "20":"Día del jubilado",
        "21":"Día de la primavera",
    },
    "10":{
        "01":"Día Internacional de las Personas de Edad",
        "02":"Día nacional del recolector de residuos",
        "04":"Día internacional del animal",
        "05":"Día mundial de los docentes",
        "08":"Día Nacional del Patrimonio Natural y Cultural Argentino",
        "09":"Día del guardaparque nacional",
        "10":"Día nacional de la danza",
        "12":"Día del respeto a la diversidad cultural",
        "13":"Día del psicólogo",
        "16":"Día mundial de la alimentación",
        "21":"Día del radioaficionado",
        "24":"Día nacional de la Astronomía",
        "28":"Día mundial de la animación",
        "29":"Día nacional del aceitero",
        "30":"Día de la educación física",
        "31":"Día mundial del ahorro",
    },
    "11":{
        "05":"Día de la aviación civil",
        "06":"Día del empleado bancario",
        "07":"Día del canillita",
        "08":"Día mundial del urbanismo",
        "10":"Día de la tradición",
        "14":"Día del tambero",
        "15":"Día del Patrimonio Arquitectónico",
        "16":"Día del deportista",
        "17":"Día de la Construcción",
        "21":"Día mundial de la televisión",
        "22":"Día de la música",
        "24":"Día del Trabajador Plástico",
        "25":"Día del marino mercante",
        "26":"Día del químico",
        "30":"Día nacional del teatro",
    },
    "12":{
        "01":"Día del ama de casa",
        "03":"Día del médico",
        "04":"Día del obrero minero",
        "09":"Día mundial de la informática",
        "10":"Día del trabajador social",
        "11":"Día nacional del tango",
        "25":"Navidad",
        "31":"Fin de año",
    },
}